//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("SchoolModel", "FK_Classroom_Teacher", "Teacher", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AytenEntityFrameworkBilgeKOLEJ_Yonetim1.Teacher), "Classroom", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AytenEntityFrameworkBilgeKOLEJ_Yonetim1.Classroom), true)]
[assembly: EdmRelationshipAttribute("SchoolModel", "FK_StudentsinSchool_Classroom", "Classroom", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AytenEntityFrameworkBilgeKOLEJ_Yonetim1.Classroom), "StudentsinSchool", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AytenEntityFrameworkBilgeKOLEJ_Yonetim1.StudentsinSchool), true)]
[assembly: EdmRelationshipAttribute("SchoolModel", "FK_Detail_StudentsinSchool", "StudentsinSchool", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AytenEntityFrameworkBilgeKOLEJ_Yonetim1.StudentsinSchool), "Detail", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AytenEntityFrameworkBilgeKOLEJ_Yonetim1.Detail), true)]
[assembly: EdmRelationshipAttribute("SchoolModel", "FK_techer_lesson_Lesson", "Lesson", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AytenEntityFrameworkBilgeKOLEJ_Yonetim1.Lesson), "techer_lesson", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AytenEntityFrameworkBilgeKOLEJ_Yonetim1.techer_lesson), true)]
[assembly: EdmRelationshipAttribute("SchoolModel", "FK_Note_StudentsinSchool", "StudentsinSchool", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AytenEntityFrameworkBilgeKOLEJ_Yonetim1.StudentsinSchool), "Note", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AytenEntityFrameworkBilgeKOLEJ_Yonetim1.Note), true)]
[assembly: EdmRelationshipAttribute("SchoolModel", "FK_StudentsinSchool_Registerated", "Registerated", System.Data.Metadata.Edm.RelationshipMultiplicity.ZeroOrOne, typeof(AytenEntityFrameworkBilgeKOLEJ_Yonetim1.Registerated), "StudentsinSchool", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AytenEntityFrameworkBilgeKOLEJ_Yonetim1.StudentsinSchool), true)]
[assembly: EdmRelationshipAttribute("SchoolModel", "FK_techer_lesson_Teacher", "Teacher", System.Data.Metadata.Edm.RelationshipMultiplicity.One, typeof(AytenEntityFrameworkBilgeKOLEJ_Yonetim1.Teacher), "techer_lesson", System.Data.Metadata.Edm.RelationshipMultiplicity.Many, typeof(AytenEntityFrameworkBilgeKOLEJ_Yonetim1.techer_lesson), true)]

#endregion

namespace AytenEntityFrameworkBilgeKOLEJ_Yonetim1
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class SchoolEntities1 : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new SchoolEntities1 object using the connection string found in the 'SchoolEntities1' section of the application configuration file.
        /// </summary>
        public SchoolEntities1() : base("name=SchoolEntities1", "SchoolEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SchoolEntities1 object.
        /// </summary>
        public SchoolEntities1(string connectionString) : base(connectionString, "SchoolEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new SchoolEntities1 object.
        /// </summary>
        public SchoolEntities1(EntityConnection connection) : base(connection, "SchoolEntities1")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Classroom> Classrooms
        {
            get
            {
                if ((_Classrooms == null))
                {
                    _Classrooms = base.CreateObjectSet<Classroom>("Classrooms");
                }
                return _Classrooms;
            }
        }
        private ObjectSet<Classroom> _Classrooms;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Detail> Details
        {
            get
            {
                if ((_Details == null))
                {
                    _Details = base.CreateObjectSet<Detail>("Details");
                }
                return _Details;
            }
        }
        private ObjectSet<Detail> _Details;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Lesson> Lessons
        {
            get
            {
                if ((_Lessons == null))
                {
                    _Lessons = base.CreateObjectSet<Lesson>("Lessons");
                }
                return _Lessons;
            }
        }
        private ObjectSet<Lesson> _Lessons;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Note> Notes
        {
            get
            {
                if ((_Notes == null))
                {
                    _Notes = base.CreateObjectSet<Note>("Notes");
                }
                return _Notes;
            }
        }
        private ObjectSet<Note> _Notes;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Registerated> Registerateds
        {
            get
            {
                if ((_Registerateds == null))
                {
                    _Registerateds = base.CreateObjectSet<Registerated>("Registerateds");
                }
                return _Registerateds;
            }
        }
        private ObjectSet<Registerated> _Registerateds;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<StudentsinSchool> StudentsinSchools
        {
            get
            {
                if ((_StudentsinSchools == null))
                {
                    _StudentsinSchools = base.CreateObjectSet<StudentsinSchool>("StudentsinSchools");
                }
                return _StudentsinSchools;
            }
        }
        private ObjectSet<StudentsinSchool> _StudentsinSchools;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<sysdiagram> sysdiagrams
        {
            get
            {
                if ((_sysdiagrams == null))
                {
                    _sysdiagrams = base.CreateObjectSet<sysdiagram>("sysdiagrams");
                }
                return _sysdiagrams;
            }
        }
        private ObjectSet<sysdiagram> _sysdiagrams;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Teacher> Teachers
        {
            get
            {
                if ((_Teachers == null))
                {
                    _Teachers = base.CreateObjectSet<Teacher>("Teachers");
                }
                return _Teachers;
            }
        }
        private ObjectSet<Teacher> _Teachers;
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<techer_lesson> techer_lesson
        {
            get
            {
                if ((_techer_lesson == null))
                {
                    _techer_lesson = base.CreateObjectSet<techer_lesson>("techer_lesson");
                }
                return _techer_lesson;
            }
        }
        private ObjectSet<techer_lesson> _techer_lesson;

        #endregion
        #region AddTo Methods
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Classrooms EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToClassrooms(Classroom classroom)
        {
            base.AddObject("Classrooms", classroom);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Details EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToDetails(Detail detail)
        {
            base.AddObject("Details", detail);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Lessons EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToLessons(Lesson lesson)
        {
            base.AddObject("Lessons", lesson);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Notes EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToNotes(Note note)
        {
            base.AddObject("Notes", note);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Registerateds EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToRegisterateds(Registerated registerated)
        {
            base.AddObject("Registerateds", registerated);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the StudentsinSchools EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToStudentsinSchools(StudentsinSchool studentsinSchool)
        {
            base.AddObject("StudentsinSchools", studentsinSchool);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the sysdiagrams EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTosysdiagrams(sysdiagram sysdiagram)
        {
            base.AddObject("sysdiagrams", sysdiagram);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the Teachers EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddToTeachers(Teacher teacher)
        {
            base.AddObject("Teachers", teacher);
        }
    
        /// <summary>
        /// Deprecated Method for adding a new object to the techer_lesson EntitySet. Consider using the .Add method of the associated ObjectSet&lt;T&gt; property instead.
        /// </summary>
        public void AddTotecher_lesson(techer_lesson techer_lesson)
        {
            base.AddObject("techer_lesson", techer_lesson);
        }

        #endregion
    }
    

    #endregion
    
    #region Entities
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="Classroom")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Classroom : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Classroom object.
        /// </summary>
        /// <param name="classroomID">Initial value of the ClassroomID property.</param>
        public static Classroom CreateClassroom(global::System.Int32 classroomID)
        {
            Classroom classroom = new Classroom();
            classroom.ClassroomID = classroomID;
            return classroom;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 ClassroomID
        {
            get
            {
                return _ClassroomID;
            }
            set
            {
                if (_ClassroomID != value)
                {
                    OnClassroomIDChanging(value);
                    ReportPropertyChanging("ClassroomID");
                    _ClassroomID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("ClassroomID");
                    OnClassroomIDChanged();
                }
            }
        }
        private global::System.Int32 _ClassroomID;
        partial void OnClassroomIDChanging(global::System.Int32 value);
        partial void OnClassroomIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Sinifi
        {
            get
            {
                return _Sinifi;
            }
            set
            {
                OnSinifiChanging(value);
                ReportPropertyChanging("Sinifi");
                _Sinifi = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Sinifi");
                OnSinifiChanged();
            }
        }
        private global::System.String _Sinifi;
        partial void OnSinifiChanging(global::System.String value);
        partial void OnSinifiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StudentID
        {
            get
            {
                return _StudentID;
            }
            set
            {
                OnStudentIDChanging(value);
                ReportPropertyChanging("StudentID");
                _StudentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StudentID");
                OnStudentIDChanged();
            }
        }
        private Nullable<global::System.Int32> _StudentID;
        partial void OnStudentIDChanging(Nullable<global::System.Int32> value);
        partial void OnStudentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TeacherID
        {
            get
            {
                return _TeacherID;
            }
            set
            {
                OnTeacherIDChanging(value);
                ReportPropertyChanging("TeacherID");
                _TeacherID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TeacherID");
                OnTeacherIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TeacherID;
        partial void OnTeacherIDChanging(Nullable<global::System.Int32> value);
        partial void OnTeacherIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_Classroom_Teacher", "Teacher")]
        public Teacher Teacher
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("SchoolModel.FK_Classroom_Teacher", "Teacher").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("SchoolModel.FK_Classroom_Teacher", "Teacher").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Teacher> TeacherReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("SchoolModel.FK_Classroom_Teacher", "Teacher");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Teacher>("SchoolModel.FK_Classroom_Teacher", "Teacher", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_StudentsinSchool_Classroom", "StudentsinSchool")]
        public EntityCollection<StudentsinSchool> StudentsinSchools
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentsinSchool>("SchoolModel.FK_StudentsinSchool_Classroom", "StudentsinSchool");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentsinSchool>("SchoolModel.FK_StudentsinSchool_Classroom", "StudentsinSchool", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="Detail")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Detail : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Detail object.
        /// </summary>
        /// <param name="detailID">Initial value of the DetailID property.</param>
        public static Detail CreateDetail(global::System.Int32 detailID)
        {
            Detail detail = new Detail();
            detail.DetailID = detailID;
            return detail;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 DetailID
        {
            get
            {
                return _DetailID;
            }
            set
            {
                if (_DetailID != value)
                {
                    OnDetailIDChanging(value);
                    ReportPropertyChanging("DetailID");
                    _DetailID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("DetailID");
                    OnDetailIDChanged();
                }
            }
        }
        private global::System.Int32 _DetailID;
        partial void OnDetailIDChanging(global::System.Int32 value);
        partial void OnDetailIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RaporluOgrenciAdı
        {
            get
            {
                return _RaporluOgrenciAdı;
            }
            set
            {
                OnRaporluOgrenciAdıChanging(value);
                ReportPropertyChanging("RaporluOgrenciAdı");
                _RaporluOgrenciAdı = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RaporluOgrenciAdı");
                OnRaporluOgrenciAdıChanged();
            }
        }
        private global::System.String _RaporluOgrenciAdı;
        partial void OnRaporluOgrenciAdıChanging(global::System.String value);
        partial void OnRaporluOgrenciAdıChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String RaporluOgrencciSoyadı
        {
            get
            {
                return _RaporluOgrencciSoyadı;
            }
            set
            {
                OnRaporluOgrencciSoyadıChanging(value);
                ReportPropertyChanging("RaporluOgrencciSoyadı");
                _RaporluOgrencciSoyadı = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("RaporluOgrencciSoyadı");
                OnRaporluOgrencciSoyadıChanged();
            }
        }
        private global::System.String _RaporluOgrencciSoyadı;
        partial void OnRaporluOgrencciSoyadıChanging(global::System.String value);
        partial void OnRaporluOgrencciSoyadıChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OnurBelgesiAlanOgrenciAdı
        {
            get
            {
                return _OnurBelgesiAlanOgrenciAdı;
            }
            set
            {
                OnOnurBelgesiAlanOgrenciAdıChanging(value);
                ReportPropertyChanging("OnurBelgesiAlanOgrenciAdı");
                _OnurBelgesiAlanOgrenciAdı = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OnurBelgesiAlanOgrenciAdı");
                OnOnurBelgesiAlanOgrenciAdıChanged();
            }
        }
        private global::System.String _OnurBelgesiAlanOgrenciAdı;
        partial void OnOnurBelgesiAlanOgrenciAdıChanging(global::System.String value);
        partial void OnOnurBelgesiAlanOgrenciAdıChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String OnurBelgesiAlanOgrenciSoyadı
        {
            get
            {
                return _OnurBelgesiAlanOgrenciSoyadı;
            }
            set
            {
                OnOnurBelgesiAlanOgrenciSoyadıChanging(value);
                ReportPropertyChanging("OnurBelgesiAlanOgrenciSoyadı");
                _OnurBelgesiAlanOgrenciSoyadı = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("OnurBelgesiAlanOgrenciSoyadı");
                OnOnurBelgesiAlanOgrenciSoyadıChanged();
            }
        }
        private global::System.String _OnurBelgesiAlanOgrenciSoyadı;
        partial void OnOnurBelgesiAlanOgrenciSoyadıChanging(global::System.String value);
        partial void OnOnurBelgesiAlanOgrenciSoyadıChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KaydıSilinenOgrenciAdı
        {
            get
            {
                return _KaydıSilinenOgrenciAdı;
            }
            set
            {
                OnKaydıSilinenOgrenciAdıChanging(value);
                ReportPropertyChanging("KaydıSilinenOgrenciAdı");
                _KaydıSilinenOgrenciAdı = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KaydıSilinenOgrenciAdı");
                OnKaydıSilinenOgrenciAdıChanged();
            }
        }
        private global::System.String _KaydıSilinenOgrenciAdı;
        partial void OnKaydıSilinenOgrenciAdıChanging(global::System.String value);
        partial void OnKaydıSilinenOgrenciAdıChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String KaydıSilinenOgrenciSoyadı
        {
            get
            {
                return _KaydıSilinenOgrenciSoyadı;
            }
            set
            {
                OnKaydıSilinenOgrenciSoyadıChanging(value);
                ReportPropertyChanging("KaydıSilinenOgrenciSoyadı");
                _KaydıSilinenOgrenciSoyadı = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("KaydıSilinenOgrenciSoyadı");
                OnKaydıSilinenOgrenciSoyadıChanged();
            }
        }
        private global::System.String _KaydıSilinenOgrenciSoyadı;
        partial void OnKaydıSilinenOgrenciSoyadıChanging(global::System.String value);
        partial void OnKaydıSilinenOgrenciSoyadıChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StudentID
        {
            get
            {
                return _StudentID;
            }
            set
            {
                OnStudentIDChanging(value);
                ReportPropertyChanging("StudentID");
                _StudentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StudentID");
                OnStudentIDChanged();
            }
        }
        private Nullable<global::System.Int32> _StudentID;
        partial void OnStudentIDChanging(Nullable<global::System.Int32> value);
        partial void OnStudentIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_Detail_StudentsinSchool", "StudentsinSchool")]
        public StudentsinSchool StudentsinSchool
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentsinSchool>("SchoolModel.FK_Detail_StudentsinSchool", "StudentsinSchool").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentsinSchool>("SchoolModel.FK_Detail_StudentsinSchool", "StudentsinSchool").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<StudentsinSchool> StudentsinSchoolReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentsinSchool>("SchoolModel.FK_Detail_StudentsinSchool", "StudentsinSchool");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<StudentsinSchool>("SchoolModel.FK_Detail_StudentsinSchool", "StudentsinSchool", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="Lesson")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Lesson : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Lesson object.
        /// </summary>
        /// <param name="lessonID">Initial value of the LessonID property.</param>
        public static Lesson CreateLesson(global::System.Int32 lessonID)
        {
            Lesson lesson = new Lesson();
            lesson.LessonID = lessonID;
            return lesson;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LessonID
        {
            get
            {
                return _LessonID;
            }
            set
            {
                if (_LessonID != value)
                {
                    OnLessonIDChanging(value);
                    ReportPropertyChanging("LessonID");
                    _LessonID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LessonID");
                    OnLessonIDChanged();
                }
            }
        }
        private global::System.Int32 _LessonID;
        partial void OnLessonIDChanging(global::System.Int32 value);
        partial void OnLessonIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String DersAdı
        {
            get
            {
                return _DersAdı;
            }
            set
            {
                OnDersAdıChanging(value);
                ReportPropertyChanging("DersAdı");
                _DersAdı = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("DersAdı");
                OnDersAdıChanged();
            }
        }
        private global::System.String _DersAdı;
        partial void OnDersAdıChanging(global::System.String value);
        partial void OnDersAdıChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DersKredi
        {
            get
            {
                return _DersKredi;
            }
            set
            {
                OnDersKrediChanging(value);
                ReportPropertyChanging("DersKredi");
                _DersKredi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DersKredi");
                OnDersKrediChanged();
            }
        }
        private Nullable<global::System.Int32> _DersKredi;
        partial void OnDersKrediChanging(Nullable<global::System.Int32> value);
        partial void OnDersKrediChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> TeacherID
        {
            get
            {
                return _TeacherID;
            }
            set
            {
                OnTeacherIDChanging(value);
                ReportPropertyChanging("TeacherID");
                _TeacherID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("TeacherID");
                OnTeacherIDChanged();
            }
        }
        private Nullable<global::System.Int32> _TeacherID;
        partial void OnTeacherIDChanging(Nullable<global::System.Int32> value);
        partial void OnTeacherIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DonemBasTarihi
        {
            get
            {
                return _DonemBasTarihi;
            }
            set
            {
                OnDonemBasTarihiChanging(value);
                ReportPropertyChanging("DonemBasTarihi");
                _DonemBasTarihi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DonemBasTarihi");
                OnDonemBasTarihiChanged();
            }
        }
        private Nullable<global::System.DateTime> _DonemBasTarihi;
        partial void OnDonemBasTarihiChanging(Nullable<global::System.DateTime> value);
        partial void OnDonemBasTarihiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> DonemBitTarihi
        {
            get
            {
                return _DonemBitTarihi;
            }
            set
            {
                OnDonemBitTarihiChanging(value);
                ReportPropertyChanging("DonemBitTarihi");
                _DonemBitTarihi = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DonemBitTarihi");
                OnDonemBitTarihiChanged();
            }
        }
        private Nullable<global::System.DateTime> _DonemBitTarihi;
        partial void OnDonemBitTarihiChanging(Nullable<global::System.DateTime> value);
        partial void OnDonemBitTarihiChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_techer_lesson_Lesson", "techer_lesson")]
        public EntityCollection<techer_lesson> techer_lesson
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<techer_lesson>("SchoolModel.FK_techer_lesson_Lesson", "techer_lesson");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<techer_lesson>("SchoolModel.FK_techer_lesson_Lesson", "techer_lesson", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="Note")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Note : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Note object.
        /// </summary>
        /// <param name="noteID">Initial value of the NoteID property.</param>
        public static Note CreateNote(global::System.Int32 noteID)
        {
            Note note = new Note();
            note.NoteID = noteID;
            return note;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NoteID
        {
            get
            {
                return _NoteID;
            }
            set
            {
                if (_NoteID != value)
                {
                    OnNoteIDChanging(value);
                    ReportPropertyChanging("NoteID");
                    _NoteID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("NoteID");
                    OnNoteIDChanged();
                }
            }
        }
        private global::System.Int32 _NoteID;
        partial void OnNoteIDChanging(global::System.Int32 value);
        partial void OnNoteIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> BirinciSınav
        {
            get
            {
                return _BirinciSınav;
            }
            set
            {
                OnBirinciSınavChanging(value);
                ReportPropertyChanging("BirinciSınav");
                _BirinciSınav = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("BirinciSınav");
                OnBirinciSınavChanged();
            }
        }
        private Nullable<global::System.Int32> _BirinciSınav;
        partial void OnBirinciSınavChanging(Nullable<global::System.Int32> value);
        partial void OnBirinciSınavChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ikinciSınav
        {
            get
            {
                return _ikinciSınav;
            }
            set
            {
                OnikinciSınavChanging(value);
                ReportPropertyChanging("ikinciSınav");
                _ikinciSınav = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ikinciSınav");
                OnikinciSınavChanged();
            }
        }
        private Nullable<global::System.Int32> _ikinciSınav;
        partial void OnikinciSınavChanging(Nullable<global::System.Int32> value);
        partial void OnikinciSınavChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SonSınav
        {
            get
            {
                return _SonSınav;
            }
            set
            {
                OnSonSınavChanging(value);
                ReportPropertyChanging("SonSınav");
                _SonSınav = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SonSınav");
                OnSonSınavChanged();
            }
        }
        private Nullable<global::System.Int32> _SonSınav;
        partial void OnSonSınavChanging(Nullable<global::System.Int32> value);
        partial void OnSonSınavChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Davranıspuan
        {
            get
            {
                return _Davranıspuan;
            }
            set
            {
                OnDavranıspuanChanging(value);
                ReportPropertyChanging("Davranıspuan");
                _Davranıspuan = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Davranıspuan");
                OnDavranıspuanChanged();
            }
        }
        private Nullable<global::System.Int32> _Davranıspuan;
        partial void OnDavranıspuanChanging(Nullable<global::System.Int32> value);
        partial void OnDavranıspuanChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> StudentID
        {
            get
            {
                return _StudentID;
            }
            set
            {
                OnStudentIDChanging(value);
                ReportPropertyChanging("StudentID");
                _StudentID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("StudentID");
                OnStudentIDChanged();
            }
        }
        private Nullable<global::System.Int32> _StudentID;
        partial void OnStudentIDChanging(Nullable<global::System.Int32> value);
        partial void OnStudentIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_Note_StudentsinSchool", "StudentsinSchool")]
        public StudentsinSchool StudentsinSchool
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentsinSchool>("SchoolModel.FK_Note_StudentsinSchool", "StudentsinSchool").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentsinSchool>("SchoolModel.FK_Note_StudentsinSchool", "StudentsinSchool").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<StudentsinSchool> StudentsinSchoolReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<StudentsinSchool>("SchoolModel.FK_Note_StudentsinSchool", "StudentsinSchool");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<StudentsinSchool>("SchoolModel.FK_Note_StudentsinSchool", "StudentsinSchool", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="Registerated")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Registerated : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Registerated object.
        /// </summary>
        /// <param name="kayıtID">Initial value of the KayıtID property.</param>
        /// <param name="veliAdi">Initial value of the VeliAdi property.</param>
        /// <param name="velisoyadi">Initial value of the Velisoyadi property.</param>
        public static Registerated CreateRegisterated(global::System.Int32 kayıtID, global::System.String veliAdi, global::System.String velisoyadi)
        {
            Registerated registerated = new Registerated();
            registerated.KayıtID = kayıtID;
            registerated.VeliAdi = veliAdi;
            registerated.Velisoyadi = velisoyadi;
            return registerated;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 KayıtID
        {
            get
            {
                return _KayıtID;
            }
            set
            {
                if (_KayıtID != value)
                {
                    OnKayıtIDChanging(value);
                    ReportPropertyChanging("KayıtID");
                    _KayıtID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("KayıtID");
                    OnKayıtIDChanged();
                }
            }
        }
        private global::System.Int32 _KayıtID;
        partial void OnKayıtIDChanging(global::System.Int32 value);
        partial void OnKayıtIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String VeliAdi
        {
            get
            {
                return _VeliAdi;
            }
            set
            {
                OnVeliAdiChanging(value);
                ReportPropertyChanging("VeliAdi");
                _VeliAdi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("VeliAdi");
                OnVeliAdiChanged();
            }
        }
        private global::System.String _VeliAdi;
        partial void OnVeliAdiChanging(global::System.String value);
        partial void OnVeliAdiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Velisoyadi
        {
            get
            {
                return _Velisoyadi;
            }
            set
            {
                OnVelisoyadiChanging(value);
                ReportPropertyChanging("Velisoyadi");
                _Velisoyadi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Velisoyadi");
                OnVelisoyadiChanged();
            }
        }
        private global::System.String _Velisoyadi;
        partial void OnVelisoyadiChanging(global::System.String value);
        partial void OnVelisoyadiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Telefon
        {
            get
            {
                return _Telefon;
            }
            set
            {
                OnTelefonChanging(value);
                ReportPropertyChanging("Telefon");
                _Telefon = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Telefon");
                OnTelefonChanged();
            }
        }
        private global::System.String _Telefon;
        partial void OnTelefonChanging(global::System.String value);
        partial void OnTelefonChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Adres
        {
            get
            {
                return _Adres;
            }
            set
            {
                OnAdresChanging(value);
                ReportPropertyChanging("Adres");
                _Adres = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Adres");
                OnAdresChanged();
            }
        }
        private global::System.String _Adres;
        partial void OnAdresChanging(global::System.String value);
        partial void OnAdresChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String email
        {
            get
            {
                return _email;
            }
            set
            {
                OnemailChanging(value);
                ReportPropertyChanging("email");
                _email = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("email");
                OnemailChanged();
            }
        }
        private global::System.String _email;
        partial void OnemailChanging(global::System.String value);
        partial void OnemailChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_StudentsinSchool_Registerated", "StudentsinSchool")]
        public EntityCollection<StudentsinSchool> StudentsinSchools
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<StudentsinSchool>("SchoolModel.FK_StudentsinSchool_Registerated", "StudentsinSchool");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<StudentsinSchool>("SchoolModel.FK_StudentsinSchool_Registerated", "StudentsinSchool", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="StudentsinSchool")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class StudentsinSchool : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new StudentsinSchool object.
        /// </summary>
        /// <param name="studentID">Initial value of the StudentID property.</param>
        /// <param name="ogrenciAdi">Initial value of the OgrenciAdi property.</param>
        /// <param name="ogrenciSoyadi">Initial value of the OgrenciSoyadi property.</param>
        /// <param name="notOrt">Initial value of the NotOrt property.</param>
        public static StudentsinSchool CreateStudentsinSchool(global::System.Int32 studentID, global::System.String ogrenciAdi, global::System.String ogrenciSoyadi, global::System.Int32 notOrt)
        {
            StudentsinSchool studentsinSchool = new StudentsinSchool();
            studentsinSchool.StudentID = studentID;
            studentsinSchool.OgrenciAdi = ogrenciAdi;
            studentsinSchool.OgrenciSoyadi = ogrenciSoyadi;
            studentsinSchool.NotOrt = notOrt;
            return studentsinSchool;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 StudentID
        {
            get
            {
                return _StudentID;
            }
            set
            {
                if (_StudentID != value)
                {
                    OnStudentIDChanging(value);
                    ReportPropertyChanging("StudentID");
                    _StudentID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("StudentID");
                    OnStudentIDChanged();
                }
            }
        }
        private global::System.Int32 _StudentID;
        partial void OnStudentIDChanging(global::System.Int32 value);
        partial void OnStudentIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OgrenciAdi
        {
            get
            {
                return _OgrenciAdi;
            }
            set
            {
                OnOgrenciAdiChanging(value);
                ReportPropertyChanging("OgrenciAdi");
                _OgrenciAdi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OgrenciAdi");
                OnOgrenciAdiChanged();
            }
        }
        private global::System.String _OgrenciAdi;
        partial void OnOgrenciAdiChanging(global::System.String value);
        partial void OnOgrenciAdiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OgrenciSoyadi
        {
            get
            {
                return _OgrenciSoyadi;
            }
            set
            {
                OnOgrenciSoyadiChanging(value);
                ReportPropertyChanging("OgrenciSoyadi");
                _OgrenciSoyadi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OgrenciSoyadi");
                OnOgrenciSoyadiChanged();
            }
        }
        private global::System.String _OgrenciSoyadi;
        partial void OnOgrenciSoyadiChanging(global::System.String value);
        partial void OnOgrenciSoyadiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> KayıtYılı
        {
            get
            {
                return _KayıtYılı;
            }
            set
            {
                OnKayıtYılıChanging(value);
                ReportPropertyChanging("KayıtYılı");
                _KayıtYılı = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KayıtYılı");
                OnKayıtYılıChanged();
            }
        }
        private Nullable<global::System.Int32> _KayıtYılı;
        partial void OnKayıtYılıChanging(Nullable<global::System.Int32> value);
        partial void OnKayıtYılıChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MezunolunanOkul
        {
            get
            {
                return _MezunolunanOkul;
            }
            set
            {
                OnMezunolunanOkulChanging(value);
                ReportPropertyChanging("MezunolunanOkul");
                _MezunolunanOkul = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MezunolunanOkul");
                OnMezunolunanOkulChanged();
            }
        }
        private global::System.String _MezunolunanOkul;
        partial void OnMezunolunanOkulChanging(global::System.String value);
        partial void OnMezunolunanOkulChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 NotOrt
        {
            get
            {
                return _NotOrt;
            }
            set
            {
                OnNotOrtChanging(value);
                ReportPropertyChanging("NotOrt");
                _NotOrt = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NotOrt");
                OnNotOrtChanged();
            }
        }
        private global::System.Int32 _NotOrt;
        partial void OnNotOrtChanging(global::System.Int32 value);
        partial void OnNotOrtChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CassroomID
        {
            get
            {
                return _CassroomID;
            }
            set
            {
                OnCassroomIDChanging(value);
                ReportPropertyChanging("CassroomID");
                _CassroomID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CassroomID");
                OnCassroomIDChanged();
            }
        }
        private Nullable<global::System.Int32> _CassroomID;
        partial void OnCassroomIDChanging(Nullable<global::System.Int32> value);
        partial void OnCassroomIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String ResimYolu
        {
            get
            {
                return _ResimYolu;
            }
            set
            {
                OnResimYoluChanging(value);
                ReportPropertyChanging("ResimYolu");
                _ResimYolu = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("ResimYolu");
                OnResimYoluChanged();
            }
        }
        private global::System.String _ResimYolu;
        partial void OnResimYoluChanging(global::System.String value);
        partial void OnResimYoluChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Boolean> DevamEdiyor
        {
            get
            {
                return _DevamEdiyor;
            }
            set
            {
                OnDevamEdiyorChanging(value);
                ReportPropertyChanging("DevamEdiyor");
                _DevamEdiyor = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DevamEdiyor");
                OnDevamEdiyorChanged();
            }
        }
        private Nullable<global::System.Boolean> _DevamEdiyor;
        partial void OnDevamEdiyorChanging(Nullable<global::System.Boolean> value);
        partial void OnDevamEdiyorChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> KayıtID
        {
            get
            {
                return _KayıtID;
            }
            set
            {
                OnKayıtIDChanging(value);
                ReportPropertyChanging("KayıtID");
                _KayıtID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("KayıtID");
                OnKayıtIDChanged();
            }
        }
        private Nullable<global::System.Int32> _KayıtID;
        partial void OnKayıtIDChanging(Nullable<global::System.Int32> value);
        partial void OnKayıtIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_StudentsinSchool_Classroom", "Classroom")]
        public Classroom Classroom
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Classroom>("SchoolModel.FK_StudentsinSchool_Classroom", "Classroom").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Classroom>("SchoolModel.FK_StudentsinSchool_Classroom", "Classroom").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Classroom> ClassroomReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Classroom>("SchoolModel.FK_StudentsinSchool_Classroom", "Classroom");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Classroom>("SchoolModel.FK_StudentsinSchool_Classroom", "Classroom", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_Detail_StudentsinSchool", "Detail")]
        public EntityCollection<Detail> Details
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Detail>("SchoolModel.FK_Detail_StudentsinSchool", "Detail");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Detail>("SchoolModel.FK_Detail_StudentsinSchool", "Detail", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_Note_StudentsinSchool", "Note")]
        public EntityCollection<Note> Notes
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Note>("SchoolModel.FK_Note_StudentsinSchool", "Note");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Note>("SchoolModel.FK_Note_StudentsinSchool", "Note", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_StudentsinSchool_Registerated", "Registerated")]
        public Registerated Registerated
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Registerated>("SchoolModel.FK_StudentsinSchool_Registerated", "Registerated").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Registerated>("SchoolModel.FK_StudentsinSchool_Registerated", "Registerated").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Registerated> RegisteratedReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Registerated>("SchoolModel.FK_StudentsinSchool_Registerated", "Registerated");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Registerated>("SchoolModel.FK_StudentsinSchool_Registerated", "Registerated", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="sysdiagram")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class sysdiagram : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new sysdiagram object.
        /// </summary>
        /// <param name="name">Initial value of the name property.</param>
        /// <param name="principal_id">Initial value of the principal_id property.</param>
        /// <param name="diagram_id">Initial value of the diagram_id property.</param>
        public static sysdiagram Createsysdiagram(global::System.String name, global::System.Int32 principal_id, global::System.Int32 diagram_id)
        {
            sysdiagram sysdiagram = new sysdiagram();
            sysdiagram.name = name;
            sysdiagram.principal_id = principal_id;
            sysdiagram.diagram_id = diagram_id;
            return sysdiagram;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String name
        {
            get
            {
                return _name;
            }
            set
            {
                OnnameChanging(value);
                ReportPropertyChanging("name");
                _name = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("name");
                OnnameChanged();
            }
        }
        private global::System.String _name;
        partial void OnnameChanging(global::System.String value);
        partial void OnnameChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 principal_id
        {
            get
            {
                return _principal_id;
            }
            set
            {
                Onprincipal_idChanging(value);
                ReportPropertyChanging("principal_id");
                _principal_id = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("principal_id");
                Onprincipal_idChanged();
            }
        }
        private global::System.Int32 _principal_id;
        partial void Onprincipal_idChanging(global::System.Int32 value);
        partial void Onprincipal_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 diagram_id
        {
            get
            {
                return _diagram_id;
            }
            set
            {
                if (_diagram_id != value)
                {
                    Ondiagram_idChanging(value);
                    ReportPropertyChanging("diagram_id");
                    _diagram_id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("diagram_id");
                    Ondiagram_idChanged();
                }
            }
        }
        private global::System.Int32 _diagram_id;
        partial void Ondiagram_idChanging(global::System.Int32 value);
        partial void Ondiagram_idChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> version
        {
            get
            {
                return _version;
            }
            set
            {
                OnversionChanging(value);
                ReportPropertyChanging("version");
                _version = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("version");
                OnversionChanged();
            }
        }
        private Nullable<global::System.Int32> _version;
        partial void OnversionChanging(Nullable<global::System.Int32> value);
        partial void OnversionChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.Byte[] definition
        {
            get
            {
                return StructuralObject.GetValidValue(_definition);
            }
            set
            {
                OndefinitionChanging(value);
                ReportPropertyChanging("definition");
                _definition = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("definition");
                OndefinitionChanged();
            }
        }
        private global::System.Byte[] _definition;
        partial void OndefinitionChanging(global::System.Byte[] value);
        partial void OndefinitionChanged();

        #endregion
    
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="Teacher")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Teacher : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new Teacher object.
        /// </summary>
        /// <param name="teacherID">Initial value of the TeacherID property.</param>
        /// <param name="ogretmenAdi">Initial value of the OgretmenAdi property.</param>
        /// <param name="ogretmenSoyadi">Initial value of the OgretmenSoyadi property.</param>
        /// <param name="bransi">Initial value of the Bransi property.</param>
        /// <param name="gorev">Initial value of the Gorev property.</param>
        public static Teacher CreateTeacher(global::System.Int32 teacherID, global::System.String ogretmenAdi, global::System.String ogretmenSoyadi, global::System.String bransi, global::System.String gorev)
        {
            Teacher teacher = new Teacher();
            teacher.TeacherID = teacherID;
            teacher.OgretmenAdi = ogretmenAdi;
            teacher.OgretmenSoyadi = ogretmenSoyadi;
            teacher.Bransi = bransi;
            teacher.Gorev = gorev;
            return teacher;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TeacherID
        {
            get
            {
                return _TeacherID;
            }
            set
            {
                if (_TeacherID != value)
                {
                    OnTeacherIDChanging(value);
                    ReportPropertyChanging("TeacherID");
                    _TeacherID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TeacherID");
                    OnTeacherIDChanged();
                }
            }
        }
        private global::System.Int32 _TeacherID;
        partial void OnTeacherIDChanging(global::System.Int32 value);
        partial void OnTeacherIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OgretmenAdi
        {
            get
            {
                return _OgretmenAdi;
            }
            set
            {
                OnOgretmenAdiChanging(value);
                ReportPropertyChanging("OgretmenAdi");
                _OgretmenAdi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OgretmenAdi");
                OnOgretmenAdiChanged();
            }
        }
        private global::System.String _OgretmenAdi;
        partial void OnOgretmenAdiChanging(global::System.String value);
        partial void OnOgretmenAdiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String OgretmenSoyadi
        {
            get
            {
                return _OgretmenSoyadi;
            }
            set
            {
                OnOgretmenSoyadiChanging(value);
                ReportPropertyChanging("OgretmenSoyadi");
                _OgretmenSoyadi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("OgretmenSoyadi");
                OnOgretmenSoyadiChanged();
            }
        }
        private global::System.String _OgretmenSoyadi;
        partial void OnOgretmenSoyadiChanging(global::System.String value);
        partial void OnOgretmenSoyadiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Bransi
        {
            get
            {
                return _Bransi;
            }
            set
            {
                OnBransiChanging(value);
                ReportPropertyChanging("Bransi");
                _Bransi = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Bransi");
                OnBransiChanged();
            }
        }
        private global::System.String _Bransi;
        partial void OnBransiChanging(global::System.String value);
        partial void OnBransiChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Gorev
        {
            get
            {
                return _Gorev;
            }
            set
            {
                OnGorevChanging(value);
                ReportPropertyChanging("Gorev");
                _Gorev = StructuralObject.SetValidValue(value, false);
                ReportPropertyChanged("Gorev");
                OnGorevChanged();
            }
        }
        private global::System.String _Gorev;
        partial void OnGorevChanging(global::System.String value);
        partial void OnGorevChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> LessonID
        {
            get
            {
                return _LessonID;
            }
            set
            {
                OnLessonIDChanging(value);
                ReportPropertyChanging("LessonID");
                _LessonID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LessonID");
                OnLessonIDChanged();
            }
        }
        private Nullable<global::System.Int32> _LessonID;
        partial void OnLessonIDChanging(Nullable<global::System.Int32> value);
        partial void OnLessonIDChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_Classroom_Teacher", "Classroom")]
        public EntityCollection<Classroom> Classrooms
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<Classroom>("SchoolModel.FK_Classroom_Teacher", "Classroom");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<Classroom>("SchoolModel.FK_Classroom_Teacher", "Classroom", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_techer_lesson_Teacher", "techer_lesson")]
        public EntityCollection<techer_lesson> techer_lesson
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedCollection<techer_lesson>("SchoolModel.FK_techer_lesson_Teacher", "techer_lesson");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedCollection<techer_lesson>("SchoolModel.FK_techer_lesson_Teacher", "techer_lesson", value);
                }
            }
        }

        #endregion
    }
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="SchoolModel", Name="techer_lesson")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class techer_lesson : EntityObject
    {
        #region Factory Method
    
        /// <summary>
        /// Create a new techer_lesson object.
        /// </summary>
        /// <param name="lessonID">Initial value of the LessonID property.</param>
        /// <param name="teacherID">Initial value of the TeacherID property.</param>
        public static techer_lesson Createtecher_lesson(global::System.Int32 lessonID, global::System.Int32 teacherID)
        {
            techer_lesson techer_lesson = new techer_lesson();
            techer_lesson.LessonID = lessonID;
            techer_lesson.TeacherID = teacherID;
            return techer_lesson;
        }

        #endregion
        #region Primitive Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 LessonID
        {
            get
            {
                return _LessonID;
            }
            set
            {
                if (_LessonID != value)
                {
                    OnLessonIDChanging(value);
                    ReportPropertyChanging("LessonID");
                    _LessonID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LessonID");
                    OnLessonIDChanged();
                }
            }
        }
        private global::System.Int32 _LessonID;
        partial void OnLessonIDChanging(global::System.Int32 value);
        partial void OnLessonIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int32 TeacherID
        {
            get
            {
                return _TeacherID;
            }
            set
            {
                if (_TeacherID != value)
                {
                    OnTeacherIDChanging(value);
                    ReportPropertyChanging("TeacherID");
                    _TeacherID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("TeacherID");
                    OnTeacherIDChanged();
                }
            }
        }
        private global::System.Int32 _TeacherID;
        partial void OnTeacherIDChanging(global::System.Int32 value);
        partial void OnTeacherIDChanged();
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String SecmeliDers
        {
            get
            {
                return _SecmeliDers;
            }
            set
            {
                OnSecmeliDersChanging(value);
                ReportPropertyChanging("SecmeliDers");
                _SecmeliDers = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("SecmeliDers");
                OnSecmeliDersChanged();
            }
        }
        private global::System.String _SecmeliDers;
        partial void OnSecmeliDersChanging(global::System.String value);
        partial void OnSecmeliDersChanged();

        #endregion
    
        #region Navigation Properties
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_techer_lesson_Lesson", "Lesson")]
        public Lesson Lesson
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lesson>("SchoolModel.FK_techer_lesson_Lesson", "Lesson").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lesson>("SchoolModel.FK_techer_lesson_Lesson", "Lesson").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Lesson> LessonReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Lesson>("SchoolModel.FK_techer_lesson_Lesson", "Lesson");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Lesson>("SchoolModel.FK_techer_lesson_Lesson", "Lesson", value);
                }
            }
        }
    
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [XmlIgnoreAttribute()]
        [SoapIgnoreAttribute()]
        [DataMemberAttribute()]
        [EdmRelationshipNavigationPropertyAttribute("SchoolModel", "FK_techer_lesson_Teacher", "Teacher")]
        public Teacher Teacher
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("SchoolModel.FK_techer_lesson_Teacher", "Teacher").Value;
            }
            set
            {
                ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("SchoolModel.FK_techer_lesson_Teacher", "Teacher").Value = value;
            }
        }
        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        [BrowsableAttribute(false)]
        [DataMemberAttribute()]
        public EntityReference<Teacher> TeacherReference
        {
            get
            {
                return ((IEntityWithRelationships)this).RelationshipManager.GetRelatedReference<Teacher>("SchoolModel.FK_techer_lesson_Teacher", "Teacher");
            }
            set
            {
                if ((value != null))
                {
                    ((IEntityWithRelationships)this).RelationshipManager.InitializeRelatedReference<Teacher>("SchoolModel.FK_techer_lesson_Teacher", "Teacher", value);
                }
            }
        }

        #endregion
    }

    #endregion
    
}
